### PR TITLE
Capitalize plist tab

### PR DESCRIPTION
**Pull request by clburlison**
Visually this tab should match the Basics and Details tabs.

### CODE REVIEW

**Comment by gregneagle** [comment]
Not convinced. "Plist" looks wrong to me. Might be happier with "Raw", or "Source".

**Comment by erikng** [comment]
Property List? Or is that too long?

**Comment by gregneagle** [comment]
I don't love it.

**Comment by erikng** [comment]
How about XML?

**Comment by gregneagle** [comment]
Nope...

**Comment by erikng** [comment]
So I know you're not a fan of "Plist" but...

https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man8/PlistBuddy.8.html

**Comment by gregneagle** [comment]
The lowercase plist doesn't bother me obviously, or I wouldn't have used it. I think there are other issues in MWA2 that deserve deeper attention...

**Comment by gregneagle** [comment]
(and "PlistBuddy" is another entry in the list of Apple's inconsistently-adhered to pattern of naming its tools with CamelCase, presumably to distinguish them from "traditional" UNIX commands. Thus "SetFile" and "SplitForks" and the like.)

**Pull request closed without merging**
