### PR TITLE
Some basic styling and behavioral fixes.

### PR DESCRIPTION
**Pull request by wollardj**
I can split these two commits if need be, but they're both pretty minor (even though Atom apparently replaced hard tabs with soft tabs and made the commits look much bigger than they really are).

### CODE REVIEW

**Comment by gregneagle** [comment]
Is the first one browser-specific? I pretty much only use Safari and don't see any difference in the layout with your changes. What am I missing?

**Comment by gregneagle** [comment]
Oh, I think I see it now after looking at the CSS changes -- you've gotten rid of the horizontal "looseness" when scrolling. CSS is definitely a challenge for me. There are lots of other little issues like that I hope other people can help fix...

**Comment by gregneagle** [comment]
No, I take that back --  I got confused which version was which when testing.
With your changes, try vertically scrolling a lengthy pkginfo or manifest (especially in the details tab). In Safari, you'll notice some horizontal "looseness" -- the content can slide back and forth slightly horizontally. I think some of my earlier "odd" CSS choices were attempts to avoid that.

But I do like the modal improvements. Those issues were on my internal list to see if I could fix.

**Comment by wollardj** [comment]
Cool. I'll look into some options for the horizontal looseness you described as soon as I get a chance. Separate pull request forthcoming.

**Comment by gregneagle** [comment]
I opened an issue: https://github.com/munki/mwa2/issues/6

**Pull request merged**
