### PR TITLE
Lock plist editor fields to vertical resizing

### PR DESCRIPTION
**Pull request by chrisgrande**
Fixes issue #16 by disabling horizontal field resizing. Fields can still be vertically resized if needed.

### CODE REVIEW

**Comment by gregneagle** [comment]
On Safari I can still do this when resizing:
image

**Comment by gregneagle** [comment]
Notice how the first column has been squeezed out of existence.

**Comment by chrisgrande** [comment]
Oops - I didn't apply the fix to the manifest editor just the pkginfo editor. New commit applies to both.

**Comment by gregneagle** [comment]
Still wonky:
image

**Comment by chrisgrande** [comment]
Hmm, I can't reproduce it - are you just dragging the resize handle in the corner of the field?
With those two commits it should only allow the fields in both editors to be resized vertically.

**Comment by gregneagle** [comment]
"are you just dragging the resize handle in the corner of the field?" yep.
"With those two commits it should only allow the fields in both editors to be resized vertically." I'm still seeing some horizontal resizing.

Also: if you disable horizontal resizing -- what happens when the browser _window_ is resized? It looks to me like the fields do not adapt their width...

**Comment by chrisgrande** [comment]
Very strange, I'm not seeing either issue. They resize on browser resize and don't budge if I try to  resize them.

**Comment by gregneagle** [comment]
_I'm in a session right now, but will be out soon_

**Comment by chrisgrande** [comment]
_Ok - I'm in the lounge area by the 100 rooms beverages._

**Comment by gregneagle** [comment]
Thanks for this fix!

**Pull request merged**
